.TH "/home/pieter-jan/Dropbox/School/2016-2017/Embedded prototyping/Python/__main__.py" 3 "Thu Jan 19 2017" "MindGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pieter-jan/Dropbox/School/2016-2017/Embedded prototyping/Python/__main__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fB__main__\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBstartServer\fP ()"
.br
.ti -1c
.RI "def \fBwhiletrue\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBgo\fP = Game('piet','pol','normal','subtile')"
.br
.ti -1c
.RI "bool \fBgameRunning\fP = False"
.br
.ti -1c
.RI "\fBdb\fP = MySQLdb\&.connect('localhost','root','root','MindGame' )"
.br
.ti -1c
.RI "\fBdbc\fP = db\&.cursor()"
.br
.ti -1c
.RI "string \fBsql\fP = 'DELETE FROM Game;'"
.br
.ti -1c
.RI "\fBthread\fP = Thread(target = startServer, args = ())"
.br
.ti -1c
.RI "\fBwhiletruethread\fP = Thread(target = whiletrue, args = ())"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MindGame from the source code\&.
