.TH "player" 3 "Thu Jan 19 2017" "MindGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, gameobj, \fBGameMode\fP, \fBLightMode\fP, \fBName\fP, \fBpin\fP)"
.br
.ti -1c
.RI "def \fBstartTime\fP (self)"
.br
.ti -1c
.RI "def \fBtimeLooping\fP (self)"
.br
.ti -1c
.RI "def \fBupdateLooping\fP (self)"
.br
.ti -1c
.RI "def \fBendGame\fP (self)"
.br
.ti -1c
.RI "def \fBwriteToSql\fP (self, sql)"
.br
.ti -1c
.RI "def \fBsetAllBallsLeds\fP (self, R, G)"
.br
.ti -1c
.RI "def \fBsetBalls\fP (self, pos)"
.br
.ti -1c
.RI "def \fBsetBrilColor\fP (self, R, G, B)"
.br
.ti -1c
.RI "def \fBgetBalls\fP (self)"
.br
.ti -1c
.RI "def \fBgetName\fP (self)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBName\fP"
.br
.ti -1c
.RI "\fBtime\fP"
.br
.ti -1c
.RI "\fBmaxTime\fP"
.br
.ti -1c
.RI "\fBGameMode\fP"
.br
.ti -1c
.RI "\fBLightMode\fP"
.br
.ti -1c
.RI "\fBpin\fP"
.br
.ti -1c
.RI "\fBstress\fP"
.br
.ti -1c
.RI "\fBballs\fP"
.br
.ti -1c
.RI "\fBpoints\fP"
.br
.ti -1c
.RI "\fBtimethread\fP"
.br
.ti -1c
.RI "\fBupdatethread\fP"
.br
.ti -1c
.RI "\fBupdateloop\fP"
.br
.ti -1c
.RI "\fBholescores\fP"
.br
.ti -1c
.RI "\fBbrilkleur\fP"
.br
.ti -1c
.RI "\fBblinkBril\fP"
.br
.ti -1c
.RI "\fBblinkOn\fP"
.br
.ti -1c
.RI "\fBgame\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  gameobj,  GameMode,  LightMode,  Name,  pin)"

.SH "Member Function Documentation"
.PP 
.SS "def endGame ( self)"

.SS "def getBalls ( self)"

.SS "def getName ( self)"

.SS "def setAllBallsLeds ( self,  R,  G)"

.SS "def setBalls ( self,  pos)"

.SS "def setBrilColor ( self,  R,  G,  B)"

.SS "def startTime ( self)"

.SS "def timeLooping ( self)"

.SS "def updateLooping ( self)"

.SS "def writeToSql ( self,  sql)"

.SH "Field Documentation"
.PP 
.SS "balls"

.SS "blinkBril"

.SS "blinkOn"

.SS "brilkleur"

.SS "game"

.SS "GameMode"

.SS "holescores"

.SS "LightMode"

.SS "maxTime"

.SS "Name"

.SS "pin"

.SS "points"

.SS "stress"

.SS "time"

.SS "timethread"

.SS "updateloop"

.SS "updatethread"


.SH "Author"
.PP 
Generated automatically by Doxygen for MindGame from the source code\&.
