.TH "Game" 3 "Thu Jan 19 2017" "MindGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBplayer1\fP, \fBplayer2\fP, \fBGameMode\fP, \fBlightMode\fP)"
.br
.ti -1c
.RI "def \fBstartGame\fP (self)"
.br
.ti -1c
.RI "def \fBgetPlayer1Name\fP (self)"
.br
.ti -1c
.RI "def \fBgetPlayer2Name\fP (self)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBplayer1\fP"
.br
.ti -1c
.RI "\fBplayer2\fP"
.br
.ti -1c
.RI "\fBGameMode\fP"
.br
.ti -1c
.RI "\fBlightMode\fP"
.br
.ti -1c
.RI "\fBcountdown\fP"
.br
.ti -1c
.RI "\fBp1\fP"
.br
.ti -1c
.RI "\fBp2\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  player1,  player2,  GameMode,  lightMode)"

.SH "Member Function Documentation"
.PP 
.SS "def getPlayer1Name ( self)"

.SS "def getPlayer2Name ( self)"

.SS "def startGame ( self)"

.SH "Field Documentation"
.PP 
.SS "countdown"

.SS "GameMode"

.SS "lightMode"

.SS "p1"

.SS "p2"

.SS "player1"

.SS "player2"


.SH "Author"
.PP 
Generated automatically by Doxygen for MindGame from the source code\&.
