.TH "/home/pieter-jan/Dropbox/School/2016-2017/Embedded prototyping/Python/game/Player.py" 3 "Thu Jan 19 2017" "MindGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pieter-jan/Dropbox/School/2016-2017/Embedded prototyping/Python/game/Player.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBplayer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBgame\&.Player\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MindGame from the source code\&.
