.TH "/home/pieter-jan/Dropbox/School/2016-2017/Embedded prototyping/Python/webBack.py" 3 "Thu Jan 19 2017" "MindGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/pieter-jan/Dropbox/School/2016-2017/Embedded prototyping/Python/webBack.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBServerSentEvent\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBwebBack\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsend_css\fP (path)"
.br
.ti -1c
.RI "def \fBsend_pics\fP (path)"
.br
.ti -1c
.RI "def \fBsend_pics_stats\fP (path)"
.br
.ti -1c
.RI "def \fBsend_js\fP (path)"
.br
.ti -1c
.RI "def \fBsend_fonts\fP (path)"
.br
.ti -1c
.RI "def \fBindex\fP ()"
.br
.ti -1c
.RI "def \fBinGame\fP (path)"
.br
.ti -1c
.RI "def \fBstats\fP ()"
.br
.ti -1c
.RI "def \fBstartInfo\fP ()"
.br
.ti -1c
.RI "def \fBgameInfo\fP (path)"
.br
.ti -1c
.RI "def \fBdebug\fP ()"
.br
.ti -1c
.RI "def \fBstartgame\fP ()"
.br
.ti -1c
.RI "def \fBstatinfo\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBnoFurtherRequests\fP = True"
.br
.ti -1c
.RI "\fBapp\fP = Flask(__name__, static_url_path='', static_path='',static_folder='')"
.br
.ti -1c
.RI "\fBdebug\fP"
.br
.ti -1c
.RI "\fBuse_reloader\fP"
.br
.ti -1c
.RI "\fBthreaded\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MindGame from the source code\&.
