.TH "webBack" 3 "Thu Jan 19 2017" "MindGame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
webBack \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBServerSentEvent\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBsend_css\fP (path)"
.br
.ti -1c
.RI "def \fBsend_pics\fP (path)"
.br
.ti -1c
.RI "def \fBsend_pics_stats\fP (path)"
.br
.ti -1c
.RI "def \fBsend_js\fP (path)"
.br
.ti -1c
.RI "def \fBsend_fonts\fP (path)"
.br
.ti -1c
.RI "def \fBindex\fP ()"
.br
.ti -1c
.RI "def \fBinGame\fP (path)"
.br
.ti -1c
.RI "def \fBstats\fP ()"
.br
.ti -1c
.RI "def \fBstartInfo\fP ()"
.br
.ti -1c
.RI "def \fBgameInfo\fP (path)"
.br
.ti -1c
.RI "def \fBdebug\fP ()"
.br
.ti -1c
.RI "def \fBstartgame\fP ()"
.br
.ti -1c
.RI "def \fBstatinfo\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBnoFurtherRequests\fP = True"
.br
.ti -1c
.RI "\fBapp\fP = Flask(__name__, static_url_path='', static_path='',static_folder='')"
.br
.ti -1c
.RI "\fBdebug\fP"
.br
.ti -1c
.RI "\fBuse_reloader\fP"
.br
.ti -1c
.RI "\fBthreaded\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def webBack\&.debug ()"

.SS "def webBack\&.gameInfo ( path)"

.SS "def webBack\&.index ()"

.SS "def webBack\&.inGame ( path)"

.SS "def webBack\&.send_css ( path)"

.SS "def webBack\&.send_fonts ( path)"

.SS "def webBack\&.send_js ( path)"

.SS "def webBack\&.send_pics ( path)"

.SS "def webBack\&.send_pics_stats ( path)"

.SS "def webBack\&.startgame ()"

.SS "def webBack\&.startInfo ()"

.SS "def webBack\&.statinfo ()"

.SS "def webBack\&.stats ()"

.SH "Variable Documentation"
.PP 
.SS "app = Flask(__name__, static_url_path='', static_path='',static_folder='')"

.SS "debug"

.SS "bool noFurtherRequests = True"

.SS "threaded"

.SS "use_reloader"

.SH "Author"
.PP 
Generated automatically by Doxygen for MindGame from the source code\&.
